spring:
  application:
    name: backend
  profiles:
    default: local
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true

server:
  shutdown: graceful

app:
  jobs:
    collection:
      scheduling-enabled: true
      initial-delay: PT30S
      fixed-delay: PT6H
